name: scripturesongs
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1+2

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.11
  audio_video_progress_bar: ^2.0.1
  get_it: ^9.2.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  http: ^1.2.1
  share_plus: ^12.0.1
  rxdart: ^0.28.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0 
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg